from tkinter import *
from tkinter import ttk
import mysql.connector
frm5 =Toplevel()
frm5.geometry('1975x100')
vs=Scrollbar(frm5,width=20,bg="yellow")
vs.pack(side=RIGHT,fill=Y)
hs=Scrollbar(frm5,orient='horizontal',width=20,bg="yellow")
hs.pack(side=BOTTOM,fill=X)
frm5.title("Employee Data")
frm5.iconbitmap("C:\\Users\\mws83\\Desktop\\tkinter\\project\\filetable_120155.ico")
style=ttk.Style()
style.theme_use("alt")
style.configure("Treeview",font="Verdana 14",background="silver",foreground="navy",rowheight=25,fieldbackground="silver")
mytree=ttk.Treeview(frm5,style="Treeview",height="300")
#define column
mytree['columns']=("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID")
#foramt
mytree.column("#1",width=170,minwidth=25,anchor=CENTER)
mytree.column("#0",width=0,minwidth=0,anchor=CENTER)
mytree.column("#2",width=170,minwidth=25,anchor=CENTER)
mytree.column("#3",width=170,minwidth=25,anchor=CENTER)
mytree.column("#4",width=350,minwidth=25,anchor=CENTER)
mytree.column("#5",width=240,minwidth=25,anchor=CENTER)
mytree.column("#6",width=170,minwidth=25,anchor=CENTER)
mytree.column("#7",width=170,minwidth=25,anchor=CENTER)
mytree.column("#8",width=170,minwidth=25,anchor=CENTER)
mytree.column("#9",width=170,minwidth=25,anchor=CENTER)
mytree.column("#10",width=170,minwidth=25,anchor=CENTER)
mytree.column("#11",width=170,minwidth=25,anchor=CENTER)
#heading
mytree.heading("#1",text="EMPLOYEE_ID",anchor=W)
mytree.heading("#2",text="FIRST_NAME",anchor=W)
mytree.heading("#3",text="LAST_NAME",anchor=W)
mytree.heading("#4",text="EMAIL",anchor=W)
mytree.heading("#5",text="PHONE_NUMBER",anchor=W)
mytree.heading("#6",text="HIRE_DATE",anchor=W)
mytree.heading("#7",text="JOB_ID",anchor=W)
mytree.heading("#8",text="SALARY",anchor=W)
mytree.heading("#9",text="COMMISSION_PCT",anchor=W)
mytree.heading("#10",text="MANAGER_ID",anchor=W)
mytree.heading("#11",text="DEPARTMENT_ID",anchor=W)
#insert data
conn = mysql.connector.connect(host='localhost',user='usr',password='123456789',database='hr')
cursor=conn.cursor()
cursor.execute("SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID =140;")
r1=(cursor.fetchall())
for i in r1:
   mytree.insert('','end',values=(i))
mytree.pack(side=TOP,fill=X)
vs.config(command=mytree.yview)
hs.config(command=mytree.xview)
frm5.mainloop()